runtime: python39
env_variables:
  CLOUD_SQL_USERNAME: roam
  CLOUD_SQL_PASSWORD: summat 
  CLOUD_SQL_DATABASE_NAME: schools
  CLOUD_SQL_CONNECTION_NAME: real-ranker-backend:us-central1:real-ranker-db
